### ISSUE TITLE
A bot can't convert karma to cash

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#101]
## Steps to reproduce
1. Logged in as a bot.
1. Having 239 total karma points .
1. Having 101 karma points available to withdraw (`You can withdraw up to 101 points`).
1. Trying to withdraw 101 karma points.

## Expected behavior
Withdraw is successfully completed.

## Actual behavior
Error with message: `A bot can't convert karma to cash`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin fixed in 7f54ae2, wait for the next release (today)

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#101` is not assigned, can't get performer

**Comment by iakunin** [comment]
@yegor256 thank you! Now it works.
