### ISSUE TITLE
Error 502 after submitting multiple projects simultaneously with bot 

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#103]
Whenever I try to submit multiple projects using a bot I got the 502 error and codexia.org become unavailable for few minutes, is this a bug or its expected behavior because of the simultaneous request, and I should put a delay between requests?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.38`

**Comment by yegor256** [comment]
@fellahi-ali should be fine now

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#103` is not assigned, can't get performer
