### ISSUE TITLE
Error 502 after submitting multiple reviews simultaneously with bot 

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#105]
The same bug as https://github.com/yegor256/codexia/issues/103 but it occurs when submitting multiple reviews instead of projects.

Whenever I try to submit multiple reviews using a bot I got the 502 error and codexia.org become unavailable for few minutes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin this is already fixed
