### ISSUE TITLE
Increase review limits for bots

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#106]
@iakunin-codexia-bot now has about 300 unsent reviews in queue. That's because of [this review quota for bots](https://github.com/yegor256/codexia/blob/241df237c90913f18eceb109bb2b6d6934140cec/objects/reviews.rb#L79).

In average @iakunin-codexia-bot creates 3 review per codexia-project.

I suggest to increase [the review quota for bots](https://github.com/yegor256/codexia/blob/241df237c90913f18eceb109bb2b6d6934140cec/objects/reviews.rb#L79) up to 300.

I can even create a pull-request for that. Of course, after @yegor256 approve.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by iakunin** [comment]
Now it's about 800 reviews in the queue on the bot side.

**Comment by iakunin** [comment]
@yegor256 everything works, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#106` is not assigned, can't get performer
