### ISSUE TITLE
/bots page

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#110]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.39`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.39`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.39`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.39`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.39`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#110` is not assigned, can't get performer
