### ISSUE TITLE
special rates for bots

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#111]

**Comment by codexia-hunter** [comment]
@yegor256 this is [my take](https://github.com/yegor256/codexia/commit/0918175b5b51ea2cebb546c8d11a7eb98c17ab70#r38645929) on the new policy! I hope you consider it.

**Comment by yegor256** [comment]
@codexia-hunter take a look: 7981f57

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.40`

**Comment by fellahi-ali** [comment]
Sorry again! I my look greaddy but I would ask for 0.8 minimum, it really worth it because a submitted project by a bot is totally equivalent to a submitted project by a human. so why a human would take 1 point and I take 0.2???

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#111` is not assigned, can't get performer
