### ISSUE TITLE
/payables

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#112]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.41`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@0eb3476e46c5, thread: pool-133-thread-1
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.10](https://github.com/zerocracy/farm): Issue: yegor256/codexia#112, Action: `created`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#112` is not assigned, can't get performer
