### ISSUE TITLE
Unable to delete bot's review

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#115]
## Steps to reproduce
1. Logged in as `@iakunin-codexia-bot`
1. Write a test-review (see https://www.codexia.org/p/11)
1. Pressing the `delete` button in web-interface (https://www.codexia.org/p/11/r/1754/delete)

## Expected behavior
Review successfully deleted.

## Actual behavior
Error during review deletion: `The bot @iakunin-codexia-bot can't delete an existing review`.

Screenshot:
![image](https://user-images.githubusercontent.com/10430347/79970862-3bb98500-849c-11ea-903c-d9d9a3eae35e.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.44`

**Comment by iakunin** [comment]
@yegor256 fixed, thanks!
