### ISSUE TITLE
Upvote count doesn't rendered on Reviews entry.   

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#118]
I got an upvote for a recent Review on Codexia:
![up voted review](https://user-images.githubusercontent.com/25110612/80207144-887c9780-8625-11ea-987d-be125a7e4e0d.jpg)

But there isn't any indication on the Review entry that it's upvoted:
 ![up voted review 0](https://user-images.githubusercontent.com/25110612/80207113-769af480-8625-11ea-8914-8194895f2963.jpg)

So I think it would be more convenient to see an upvote counter on the Review entry.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fellahi-ali fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#118` is not assigned, can't get performer
