### ISSUE TITLE
Incorrect "author" in GET /recent.json response

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#119]
## Steps to reproduce
Send a GET request to `https://www.codexia.org/recent.json` with corresponding bot token

## Actual behavior
Incorrect "author" field in ALL items in response: it looks like an object hash:

```
{
    "id": 885,
    "coordinates": "semantic-machines/veda",
    "author": "#<Xia::Author:0x0000563de3207a70>",
    "deleted": null,
    "badges": [
      "L1"
    ],
    "created": "2020-04-24 10:50:01 +0000"
  }
```

## Expected behavior
Real author of [project with id=885](https://www.codexia.org/p/885) is `fellahi-ali`, therefore api response should be like this:

```
{
    "id": 885,
    "coordinates": "semantic-machines/veda",
    "author": "fellahi-ali",
    "deleted": null,
    "badges": [
      "L1"
    ],
    "created": "2020-04-24 10:50:01 +0000"
  }
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin should be fixed now

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.46`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#119` is not assigned, can't get performer
