### ISSUE TITLE
Wrong project author on /recent page

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#122]
## Steps to reproduce
1. Logged in as `@iakunin`
1. Open https://www.codexia.org/recent page

## Actual behavior
Mismatching author on /recent page and on the project page.
For example, project: https://www.codexia.org/p/990
On the project page author is `@codexia-hunter`

![image](https://user-images.githubusercontent.com/10430347/80309247-7d1f9c80-87dc-11ea-9bf9-76506fcd572b.png)

On the /recent page author is `@iakunin` (user I'm currently logged in).

![image](https://user-images.githubusercontent.com/10430347/80309262-a17b7900-87dc-11ea-88dd-85146ccf549f.png)

## Expected behavior
Author must be the same both on the project page and on the /recent page.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by iakunin** [comment]
Fixed.

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#122` is not assigned, can't get performer
