### ISSUE TITLE
Cannot see extra-karma for review per L1+ project

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#123]
https://www.codexia.org/terms says that:
> +0.80 | per each review you submitted for L1+ project

But I cannot see any of these karma points for `@iakunin-codexia-bot`.

Is this feature really working now? Could you give me a hint, where can I check if it works?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin do you have any projects that are L1? Here is the full list of them: https://www.codexia.org/recent?badges=L1 None of them were submitted by your bot, as far as I can tell...

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#123` is not assigned, can't get performer
