### ISSUE TITLE
karam points to withdraw calculation seems to be wrong! 

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#127]
The karma point available for withdrawal seems to be wrong.
Usually a user can't withdraw if he has less than 100 points (as stated by terms)
 
![image](https://user-images.githubusercontent.com/25110612/80372536-97fd1a00-888b-11ea-947b-ddade1866109.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fellahi-ali fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#127` is not assigned, can't get performer
