### ISSUE TITLE
Telegram notification shows an object hash instead of author name 

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#128]
[Tacky](https://github.com/yegor256/tacky) object hash is displayed instead of the actual submitter user name.

![author-name-telegram-notif](https://user-images.githubusercontent.com/25110612/80373235-a8fa5b00-888c-11ea-93c4-9cc584531c8b.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fellahi-ali tested and fixed, thanks!
