### ISSUE TITLE
Description of `too-small` bot

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#129]
@yegor256 could you describe how `too-small` bot should handle the cases with flipping LoC above and below the limit (5K)?

It would be great if you give me a couple of examples.

Thanks.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin here: https://github.com/iakunin/codexia-bot/pull/118

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#129` is not assigned, can't get performer
