### ISSUE TITLE
/submit endpoint is treating Bots as regular User

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#131]
The `/submit` end point is behaving in similar way for Bots as for regular Users.
and I think this bug is also introduced in the commit "tacky", [here](https://github.com/yegor256/codexia/commit/11f126e60a43bdfdbdce6bc4aaa3197e204980f6#r38799393).

### The bot is not allowed to submit more than 6 projects, and note the name is not correct.  
![submit-bot-too-fast](https://user-images.githubusercontent.com/25110612/80495421-ce0bce00-895f-11ea-819d-14f1428fe2a3.jpg)

### And this project is submitted by a Bot and is has been reported to Telegram, where it shouldn't
![bot-submit-telegram](https://user-images.githubusercontent.com/25110612/80495729-3490ec00-8960-11ea-827f-ab8b281bab71.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.48`

**Comment by yegor256** [comment]
@fellahi-ali please, try now

**Comment by fellahi-ali** [comment]
> @fellahi-ali please, try now

@yegor256 It works now, very thanks.

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#131` is not assigned, can't get performer
