### ISSUE TITLE
Bots can't delete their own projects

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#135]
I've tried to delete projects submitted by codexia-hunter, but it seems it's not implemented.
![delete-proj-bot](https://user-images.githubusercontent.com/25110612/81225872-db6d2c00-8fe1-11ea-8404-a7406f32fe54.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fellahi-ali thanks, fixed, wait for the next release please

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#135` is not assigned, can't get performer

**Comment by fellahi-ali** [comment]
@yegor256 I think something is missing in the `fix` could you please check my comments
[here](https://github.com/yegor256/codexia/commit/08787be9b3790c299b18ef00d54f39f6b943b1e9#r39006114) and [here](https://github.com/yegor256/codexia/commit/08787be9b3790c299b18ef00d54f39f6b943b1e9#r39006187)
