### ISSUE TITLE
Wrong URL for codexia-hunter bot in README file

### ISSUE THREAD

**Issue by alhadhrami** [yegor256/codexia#138]
The URL for the codexia-bot (second bullet point [here](https://github.com/yegor256/codexia)) is [this page](https://github.com/iakunin/codexia-hunter) but it is 404.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alhadhrami fixed in 37d7d80 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#138` is not assigned, can't get performer
