### ISSUE TITLE
veils

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#141]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.53`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#141` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.54`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.55`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.55`
