### ISSUE TITLE
Still getting penalty when deleting own projects  

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#144]
A user is still getting a penalty even when he delete his own submitted project: 

![deleted-proj-by-fellahi-ali](https://user-images.githubusercontent.com/25110612/81727508-fbd53480-9480-11ea-97b3-08d9655f2ce1.jpg)

![delete-own-proj-penalty](https://user-images.githubusercontent.com/25110612/81727158-6d60b300-9480-11ea-9f12-484b42a6d383.jpg)

I have left a [comment](https://github.com/yegor256/codexia/commit/08787be9b3790c299b18ef00d54f39f6b943b1e9#r39006187) where I think this bug is introduced!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.57`

**Comment by yegor256** [comment]
@fellahi-ali should be fine now, please check

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#144` is not assigned, can't get performer
