### ISSUE TITLE
[Suggestion] Add URL link to specific review/project from my profile

### ISSUE THREAD

**Issue by alhadhrami** [yegor256/codexia#148]
Currently, on my profile, I can see the IDs of the projects and reviews that got me karma points. But I can't go to that specific review or project.

I know for the project ID, I can just go to URL "/p/#id", which is cumbersome, but that's not possible for reviews. So I think it is a good idea to add a URL to the project at least, and for the review too hopefully.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alhadhrami should be fixed, try now

**Comment by alhadhrami** [comment]
@yegor256 Looks nice. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#148` is not assigned, can't get performer
