### ISSUE TITLE
[Suggestion] Enable paging on karma page

### ISSUE THREAD

**Issue by vblinden** [yegor256/codexia#152]
I think we should enable paging on the Karma page (/karma) so the user can see what happens to his/her points. For example: why is it negative, or why is postive?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.61`

**Comment by yegor256** [comment]
@vblinden should be OK now, try please

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#152` is not assigned, can't get performer
