### ISSUE TITLE
switch to Ruby

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#59]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#59` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`
