### ISSUE TITLE
Internal server error /recent

### ISSUE THREAD

**Issue by g4s8** [yegor256/codexia#64]
After login at https://www.codexia.org/ I've redirected to https://www.codexia.org/recent but got `Internal server error` with 500 status code.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 works fine now

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#64` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
