### ISSUE TITLE
/karma and withdrawals

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#65]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.9`

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#65` is not assigned, can't get performer
