### ISSUE TITLE
quotas

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#67]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.12`

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#67` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.14`
