### ISSUE TITLE
Make all repo name clickable

### ISSUE THREAD

**Issue by g4s8** [yegor256/codexia#74]
Now only small GitHub icon near repo name at project page is clickable. I always try to click repo coordinates text. Please make all text clickable, not only icon.
![scrot-2020-02-08-21:38:05](https://user-images.githubusercontent.com/1524988/74090381-c274dd80-4abb-11ea-8da7-7414bd9eb807.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.20`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#74` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
