### ISSUE TITLE
rules for HackerNews robot

### ISSUE THREAD

**Issue by mmbug** [yegor256/codexia#75]
do we have to add all projects from HackerNews when parsing new stories by robot? 
does robot have to check stars before adding or something?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@mmbug[/z](https://www.0crat.com/u/mmbug) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by mmbug** [comment]
fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#75` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
