### ISSUE TITLE
Unable to get project reviews via API (GET /p/123.json?page=)

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#79]
## Steps to reproduce
I'm trying to get reviews for [project with id=18](https://www.codexia.org/p/18) via API:
```
curl --location --request GET 'https://www.codexia.org/p/18.json' --header 'X-Codexia-Token: <my-token-here>'
```

## Expected result
Valid json-array in response.

## Actual result
HTML of the page https://www.codexia.org/p/18.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin fixed, thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.23`

**Comment by iakunin** [comment]
@yegor256 fixed. Thank you for such a rapid response!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#79` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
