### ISSUE TITLE
Review format (Markdown) should be described

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#80]
- [ ] Markdown review format should be described in project documentation (with a link to particular Markdown dialect).
- [ ] Description of "submit a review" API-endpoint on [this page](https://www.codexia.org/api) should also contain a note (or a link to documentation) describing such format.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.33`

**Comment by yegor256** [comment]
@iakunin fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#80` is not assigned, can't get performer

**Comment by iakunin** [comment]
@yegor256 now is much better, thank you!
