### ISSUE TITLE
Author mismatch on /recent page and on project page

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#81]
## Steps to reproduce
1. I logged in as `iakunin`
1. I open https://www.codexia.org/recent page and see the latest project `ozankasikci/vim-man` added by `iakunin-codexia-bot`:
![image](https://user-images.githubusercontent.com/10430347/74584731-790a1e00-4fe6-11ea-8368-4796d3d44120.png)
1. I open this project (https://www.codexia.org/p/22) and see that the author is differ from `iakunin-codexia-bot`:
![image](https://user-images.githubusercontent.com/10430347/74584726-6ee81f80-4fe6-11ea-9a5b-a09220e6b0da.png)

## Expected behavior
Author on the /recent page is the same as on the project page.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin fixed, try it

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#81` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
@yegor256 thank you: now it's fixed.
