### ISSUE TITLE
Unable to submit `dalibo/pg_activity` project

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#82]
## Steps to reproduce
1. Open https://www.codexia.org/submit page.
1. Type `dalibo/pg_activity`.
1. Click "Add" button.

## Expected behavior
Project successfully submitted, because it exists on github (https://github.com/dalibo/pg_activity)

## Actual behavior
Unable to submit project. `Coordinates are wrong` error occurs during submitting.
![image](https://user-images.githubusercontent.com/10430347/74609136-29b41280-50f8-11ea-8c42-fa57fd251510.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#82` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
@yegor256 thank you! I've successfully added this project: https://www.codexia.org/p/52
