### ISSUE TITLE
Page parameter is not working in `GET /recent.json?page=...` endpoint

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#83]
## Steps to reproduce
1. Call `GET https://www.codexia.org/recent.json?page=1`
1. Call `GET https://www.codexia.org/recent.json?page=2`

## Expected behavior
Correct page switching (different content on different pages).

## Actual behavior
The same content on page 1 and on page 2.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.25`

**Comment by yegor256** [comment]
@iakunin done, try it

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#83` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
@yegor256 now it works as expected, thank you.
