### ISSUE TITLE
Accidentally added python-file

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#84]
There is a file [a.py](https://github.com/yegor256/codexia/blob/master/a.py) in the project's root dir.

Seems that it was added by accident in [this commit](https://github.com/yegor256/codexia/commit/baa529ccce0f99a713875c86129e85b6359ef318#diff-4503e1c7f2532ff8b96fdd60367579c0) and should be removed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#84` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
