### ISSUE TITLE
Unable to withdraw karma-points

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#85]
## Steps to reproduce
1. Log in as `iakunin-codexia-bot`.
1. Go to https://www.codexia.org/karma page.
1. Type wallet id: `97a324f5d1e2b03f`.
1. Type amount of karma to withdraw (any amount).

## Expected behavior
Requested amount of karma-points successfully converted to ZLD.

## Actual behavior
* Error message `Not enough karma to pay that much` when requested karma more than 4.
* Error message `You need to have more than 100 points to cash out` when requested karma less or equal to 4.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@iakunin this is by design. You can't withdraw unless you have 100+ points.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.26`

**Comment by yegor256** [comment]
@iakunin try now

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.27`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#85` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by iakunin** [comment]
> @iakunin this is by design. You can't withdraw unless you have 100+ points.

@yegor256 got it, thanks. Now I can see an appropriate message at /karma page ("You can't withdraw anything at the moment").

**Comment by iakunin** [comment]
@yegor256 it's still unable to withdraw despite that it's more than 100 karma points on iakunin-codexia-bot's balance.

![image](https://user-images.githubusercontent.com/60966807/76358630-c8fcac00-632a-11ea-9744-7c689d230b19.png)
