### ISSUE TITLE
User name is missing in welcome message

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#86]
When login to codexia.org, I think my user name should appear in the welcome message:

![bug_welcom_msg](https://user-images.githubusercontent.com/25110612/74923339-e7792280-53d0-11ea-9d8b-057dcf5f537a.jpg)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.28`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.29`

**Comment by yegor256** [comment]
@fellahi-ali it's fixed, thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#86` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
