### ISSUE TITLE
Unable to submit project with coordinates contains upper case letters

### ISSUE THREAD

**Issue by fellahi-ali** [yegor256/codexia#87]
Hi
I've tried to submit [this](https://github.com/ardalis/GuardClauses) project but got the error message
>Coordinates "ardalis/GuardClauses" are wrong

I think because it contains UPPERCASE letters!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@fellahi-ali fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#87` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
