### ISSUE TITLE
Review creation should be idempotent

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#90]
## Problem
During bot lifetime it's possible that the review will be sent multiple times.

It could happen when bot crashes. After bot recovering he should be able to safely resend all the reviews he created.

Now it's impossible to resend all the reviews created by bot.

## Solution

Add new parameter in review submission api-endpoint (`POST /p/123/post`): 
* external_identifier (string, optional).

This `external_identifier` must be unique within user.

If user trying to create review with the same `external_identifier` and `text` multiple times the response must be the same (json containing codexia review_id).

If user trying to create review with the same `external_identifier` but with the changed `text` there must be an error.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT4L4490E) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/codexia/issues/90) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CT4L4490E/4ffe13e4-5d9d-4a76-8aca-b93f807f91af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.30`

**Comment by yegor256** [comment]
@iakunin should work now, please check

**Comment by iakunin** [comment]
@yegor256 now review creation is idempotent, thanks. But some other problem appeared: https://github.com/yegor256/codexia/issues/94
