### ISSUE TITLE
Markdown format is not supported in review

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#91]
## Steps to reproduce
Submit a review with a correct markdown link. 
For example: `This project found on Hackernews: [link](https://news.ycombinator.com/item?id=22254793)`

## Expected behavior
The link in review is clickable (text wrapped in `<a></a>` html-tag).

## Actual behavior
The link in review is not clickable (there is no `<a></a>` html-tag).

## Example
https://www.codexia.org/p/19

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#91](https://github.com/yegor256/codexia/issues/91) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CT4L4490E/9ed842dc-f174-4dce-8dde-bb38f3e899b0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.32`

**Comment by yegor256** [comment]
@iakunin should be OK in the next release

**Comment by iakunin** [comment]
@yegor256 now the problem is gone. Many thanks.
