### ISSUE TITLE
Review submission for deleted project

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#92]
## Steps to reproduce
1. Find a deleted project (e.g. https://www.codexia.org/p/18)
1. Try to submit a review for it

## Actual behavior
It's available to submit review for deleted project (e.g. review #104 for https://www.codexia.org/p/18),

## Expected behavior
It's unable to submit review for deleted project.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin fixed in a764b45, will be released soon

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#92` is not assigned, can't get performer

**Comment by iakunin** [comment]
@yegor256 now the problem is gone. Many thanks.
