### ISSUE TITLE
Withdrawal doesn't affect karma balance

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#93]
## Steps to reproduce
1. Go to [karma page](https://www.codexia.org/karma)
1. Perform withdraw withing available karma-points

## Expected result
Karma balance decreases after each withdrawal.

## Actual result
Karma balance doesn't change.

## Example
User: `iakunin-codexia-bot`
Screenshot:
![image](https://user-images.githubusercontent.com/10430347/76682771-e3c36f00-660f-11ea-9965-0a3003d488a6.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.31`

**Comment by yegor256** [comment]
@iakunin should be fixed, try again please

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#93` is not assigned, can't get performer
