### ISSUE TITLE
the website always logs out

### ISSUE THREAD

**Issue by mmbug** [yegor256/codexia#95]
it logs out almost every time I try to reload the website. seems like we need to change session expiration time

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@mmbug works great for me. Never does this. Maybe you change your IP very often? Pay attention to the IP address you see at the bottom of the page. It stays the same?

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#95` is not assigned, can't get performer
