### ISSUE TITLE
Create api-endpoint for getting project by id

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#97]
Api-endpoint for getting project by id is required for periodic checking project status (is deleted or not) by bot.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iakunin what's wrong with `GET /p/123.json`?

**Comment by iakunin** [comment]
@yegor256 `GET /p/123.json` - it's an entry point for listing all reviews per project, not for getting a project.

**Comment by yegor256** [comment]
@iakunin you are right, I added `/p/123.json` and `/p/123/reviews.json`, see aea0b9c

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#97` is not assigned, can't get performer

**Comment by iakunin** [comment]
@yegor256 many thanks for your rapid feedback.
